// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg-x6rCKmMFyh_Gh-WRcbxbpuh0Hi_fpQ',
    appId: '1:315695684466:web:00900502747d699258dbeb',
    messagingSenderId: '315695684466',
    projectId: 'prm392-kitchen',
    authDomain: 'prm392-kitchen.firebaseapp.com',
    storageBucket: 'prm392-kitchen.firebasestorage.app',
    measurementId: 'G-DHQ7TRWYPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_Sb0EiyMTvnBfhqQOWMcLN52iMqY219I',
    appId: '1:315695684466:android:0631641c850f867b58dbeb',
    messagingSenderId: '315695684466',
    projectId: 'prm392-kitchen',
    storageBucket: 'prm392-kitchen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-u_b1__esv0BO9be3DooLrvLsqCUwBBk',
    appId: '1:315695684466:ios:635fef132c97df5a58dbeb',
    messagingSenderId: '315695684466',
    projectId: 'prm392-kitchen',
    storageBucket: 'prm392-kitchen.firebasestorage.app',
    androidClientId: '315695684466-7dokaa89rh213mojlio2cvdrmmmrrqkb.apps.googleusercontent.com',
    iosClientId: '315695684466-tljknutgjmbgva0f2hf44bpk5p0j57ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-u_b1__esv0BO9be3DooLrvLsqCUwBBk',
    appId: '1:315695684466:ios:635fef132c97df5a58dbeb',
    messagingSenderId: '315695684466',
    projectId: 'prm392-kitchen',
    storageBucket: 'prm392-kitchen.firebasestorage.app',
    androidClientId: '315695684466-7dokaa89rh213mojlio2cvdrmmmrrqkb.apps.googleusercontent.com',
    iosClientId: '315695684466-tljknutgjmbgva0f2hf44bpk5p0j57ka.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg-x6rCKmMFyh_Gh-WRcbxbpuh0Hi_fpQ',
    appId: '1:315695684466:web:c98b7f6957450d8f58dbeb',
    messagingSenderId: '315695684466',
    projectId: 'prm392-kitchen',
    authDomain: 'prm392-kitchen.firebaseapp.com',
    storageBucket: 'prm392-kitchen.firebasestorage.app',
    measurementId: 'G-T8K749NQF4',
  );
}
